#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    instance:
#    preferIpAddress: true
#spring:
#  application:
#    name: eurekaclient

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
server:
  port: 8761

